name: Actions on Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd tools
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd ..
        
    - name: Make catalog by tools
      run: |
        cd tools
        python ./make_catalog.py
        cd ..
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A .
        git commit -m "Catalog: Auto build" -a
      continue-on-error: true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
      continue-on-error: true

    - name: Sync repository to coding
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/danmaqua/danmaqua-data.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "git@e.coding.net:fython/danmaqua/damaqua-data.git"
        DESTINATION_BRANCH: "master"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
