name: Sync GitHub Pages to Coding.net Pages

on: [push]

jobs:
  repo-sync:

    runs-on: ubuntu-latest

    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/danmaqua/danmaqua-data.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "git@e.coding.net:fython/danmaqua/damaqua-data.git"
        DESTINATION_BRANCH: "master"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
